# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raymond Cheng
email: me@raymondcheng.net
description: > # this means to ignore newlines until "baseurl:"
  Homepage for Raymond Cheng
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://raymondcheng.net" # the base hostname & protocol for your site
twitter_username: RaymondCheng00
github_username:  ryscheng

# Serve settings
port: 8000


# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  input: GFM #Github-Flavored Markdown
